<a href="https://colab.research.google.com/github/Haridasaravind/CS612/blob/main/CS612.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip install biopython

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import os
import random
from Bio import SeqIO

def read_fasta(directory='.'):
    # Obtain a list of all files with the .fas extension in the specified directory
    fas_files = [f for f in os.listdir(directory) if f.endswith('.fas')]
    # Select a random .fas file from the list
    selected_file = random.choice(fas_files)
    print(f"Selected File: {selected_file}")

    # Read the multiple sequence alignment (MSA) file
    records = SeqIO.parse(os.path.join(directory, selected_file), "fasta")

    # Dictionary to store sequences grouped by family
    sequences_by_family = {}

    # Process each sequence record
    for record in records:
        # Check if the record ID contains an underscore
        if '_' in record.id:
            # Extract family information from the record ID
            family = record.id.split("_")[1]

            # Add the sequence to the corresponding family in the dictionary
            if family in sequences_by_family:
                sequences_by_family[family].append(record.seq)
            else:
                sequences_by_family[family] = [record.seq]
        else:
            print(f"Warning: Skipping record with ID '{record.id}' because it does not contain an underscore")

    # Print summary statistics
    total_sequences = sum(len(sequences) for sequences in sequences_by_family.values())
    print(f"Total sequences: {total_sequences}")
    
    # Uncomment the following code to print the unique families
    # print(f"Total unique families: {len(sequences_by_family)}")
    # for family, sequences in sequences_by_family.items():
    #     print(f"Family {family}: {len(sequences)} sequences")

    # Uncomment the following code to print the sequences grouped by family
    # for family, sequences in sequences_by_family.items():
    #     print(f"\nFamily: {family}")
    #     for sequence in sequences:
    #         print(sequence)
    
    return sequences_by_family

sequences = read_fasta()

print(sequences)

Selected File: YDBL_YNBE_20_id90.fas
Total sequences: 112
{'C1DQP2': [Seq('-----------------NEAMGALSGAKARGQLGEMPNGYLGVV--GDQAEEIA...GLF')], 'Q12MD2': [Seq('MKS--FSCLIVGLLLSFQAMALTLQEAKSQGFVGEQLNGYLGLVQTTDEAKALM...SLF')], 'Q8KBR2': [Seq('-----------LAASAASAFALDLETARAKGLVGEVDNGYIAIPPAGTEAQQLV...DIF')], 'F9ZKS4': [Seq('-----------------PVWADSLENLRASGAIGEANTGYV-----EPGAQAEA...DIF')], 'Q5QUL0': [Seq('-MKL-TAVLIAFIGLSSPAQQLNLEDAKEQGLVGEKPDGYLGVVKSTETAEQIV...GLF')], 'F6A9C7': [Seq('LIK--FAGLLLLLSLSLPAHAISLNDAKASGQLGEMPNGYLGVVKSGGQADEIA...GLF')], 'G7EMM2': [Seq('MNTKLNIILVSAVCMSFSAWAISLDDAKNQGLVGEDSSGYLGLVVQNEEAKAVV...ELF')], 'D4F5H1': [Seq('---LGILLALS--LASPA-WALTLDEARASGRVGETLSGYLAARSQDAETLALV...GLF')], 'B6VL59': [Seq('----------------------TLNEAKQQGLVGETFSGYLAVV--DIQAQALV...GLF')], 'I0DZW5': [Seq('MKTIFQALMISGLF-VFSAAALTVDEAKNQGLVGETLSGYLAVVTGNAEVDELV...DLF')], 'G0EA84': [Seq('MRKRLLTATLALMLLSSPALALTLNEARAQGRVGETLNGYLAPLKQDAQTLALV...DLF')], 'Q083T0': [Seq('MKSR-TAVCLTSLLWCTTAWAMTLQEAKTARLVG

In [ ]:
import random

def read_sequence(sequences):
    # Flatten the list of sequences
    all_sequences = [seq for seq_list in sequences.values() for seq in seq_list]
    # Select a random sequence from the list
    return random.choice(all_sequences)


In [ ]:
seq = read_sequence(sequences)
print(seq)

----------------------TLNEAKQQGLVGETFSGYLAVV--DIQAQALVIKINQAREKKYAEVATSNNISTEQVAKLAGEKLVNRAEPGEYVQG-NGQWLKK---------MSSLILSGCV-RLEVATPEKPININMNVKIEHEIHVKIDKQIEEMLKSNTGLF


In [ ]:
from numpy.core.fromnumeric import amin
import numpy as np

def one_hot_encoding(seq):
    # Define the amino acid alphabet
    amino_acids = 'ACDEFGHIKLMNPQRSTVWY'
    # Create a dictionary to map each amino acid to its index in the alphabet
    aa_to_index = {aa: i for i, aa in enumerate(amino_acids)}
    # Initialize the one-hot encoded array
    one_hot = np.zeros([len(seq), len(amino_acids)])
    # Set the appropriate elements to 1
    for i, aa in enumerate(seq):
      if aa in aa_to_index:
        one_hot[i, aa_to_index[aa]] = 1
    return one_hot


In [ ]:
one_hot = one_hot_encoding(seq)
np.set_printoptions(threshold=np.inf)
print(one_hot)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [94]:
# Auto encoder 

from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model
import numpy as np

# Define the amino acid alphabet
amino_acids = 'ACDEFGHIKLMNPQRSTVWY-'

def one_hot_encoding(seq):
    # Create a dictionary to map each amino acid to its index in the alphabet
    aa_to_index = {aa: i for i, aa in enumerate(amino_acids)}
    # Initialize the one-hot encoded array
    one_hot = np.zeros((len(seq), len(amino_acids)))
    # Set the appropriate elements to 1
    for i, aa in enumerate(seq):
        if aa in aa_to_index:
            one_hot[i, aa_to_index[aa]] = 1
    return one_hot

# Define the size of the latent space
latent_dim = 32

# Define the architecture of the autoencoder
input_seq = Input(shape=(None, len(amino_acids)))
encoded = Dense(latent_dim, activation='relu')(input_seq)
decoded = Dense(len(amino_acids), activation='softmax')(encoded)
autoencoder = Model(input_seq, decoded)

# Compile the autoencoder model
autoencoder.compile(optimizer='adam', loss='categorical_crossentropy')

# Encode the sequence using one-hot encoding
seq_encoded = one_hot_encoding(seq).reshape(1, -1, len(amino_acids))

In [95]:
# Train the autoencoder on the encoded sequence
autoencoder.fit(seq_encoded, seq_encoded, epochs=100)

Epoch 1/100
1/1 [==============================] - 1s 739ms/step - loss: 3.0023
Epoch 2/100
1/1 [==============================] - 0s 12ms/step - loss: 2.9952
Epoch 3/100
1/1 [==============================] - 0s 10ms/step - loss: 2.9880
Epoch 4/100
1/1 [==============================] - 0s 11ms/step - loss: 2.9809
Epoch 5/100
1/1 [==============================] - 0s 12ms/step - loss: 2.9738
Epoch 6/100
1/1 [==============================] - 0s 15ms/step - loss: 2.9667
Epoch 7/100
1/1 [==============================] - 0s 17ms/step - loss: 2.9596
Epoch 8/100
1/1 [==============================] - 0s 12ms/step - loss: 2.9525
Epoch 9/100
1/1 [==============================] - 0s 10ms/step - loss: 2.9455
Epoch 10/100
1/1 [==============================] - 0s 11ms/step - loss: 2.9384
Epoch 11/100
1/1 [==============================] - 0s 12ms/step - loss: 2.9313
Epoch 12/100
1/1 [==============================] - 0s 12ms/step - loss: 2.9242
Epoch 13/100
1/1 [==============================

In [ ]:
# Use the autoencoder to encode and decode the sequence
seq_decoded = autoencoder.predict(seq_encoded)

1/1 [==============================] - 0s 196ms/step


In [ ]:
# Compute reconstruction error metrics
cross_entropy = -np.mean(np.sum(seq_encoded * np.log(seq_decoded), axis=-1))
same_aa_accuracy = np.mean(np.argmax(seq_encoded, axis=-1) == np.argmax(seq_decoded, axis=-1))
most_common_aa_accuracy = np.mean(np.argmax(seq_encoded.sum(axis=0), axis=-1) == np.argmax(seq_decoded.sum(axis=0), axis=-1))

In [ ]:
print("Cross-entropy:", cross_entropy)
print("Same amino acid accuracy:", same_aa_accuracy)
print("Most common amino acid accuracy:", most_common_aa_accuracy)

Cross-entropy: 2.1078780508605686
Same amino acid accuracy: 0.8994082840236687
Most common amino acid accuracy: 0.8994082840236687


In [ ]:
#decoding

from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model
import numpy as np

def one_hot_encoding(seq):
    # Define the amino acid alphabet
    amino_acids = 'ACDEFGHIKLMNPQRSTVWY-'
    # Create a dictionary to map each amino acid to its index in the alphabet
    aa_to_index = {aa: i for i, aa in enumerate(amino_acids)}
    # Initialize the one-hot encoded array
    one_hot = np.zeros((len(seq), len(amino_acids)))
    # Set the appropriate elements to 1
    for i, aa in enumerate(seq):
        if aa in aa_to_index:
            one_hot[i, aa_to_index[aa]] = 1
    return one_hot

def decode_sequence(one_hot_seq):
    # Define the amino acid alphabet
    amino_acids = 'ACDEFGHIKLMNPQRSTVWY-'
    # Convert the one-hot encoded sequence back into an amino acid sequence
    return ''.join([amino_acids[i] for i in np.argmax(one_hot_seq, axis=-1)])

# Define the size of the latent space
latent_dim = 32

# Define the autoencoder architecture
input_seq = Input(shape=(None, len(amino_acids)))
encoded = Dense(latent_dim, activation='relu')(input_seq)
decoded = Dense(len(amino_acids), activation='softmax')(encoded)
autoencoder = Model(input_seq, decoded)

# Compile the autoencoder model
autoencoder.compile(optimizer='adam', loss='categorical_crossentropy')


# Encode the sequence using one-hot encoding
seq_encoded = one_hot_encoding(seq).reshape(1, -1, len(amino_acids))

# Train the autoencoder on the encoded sequence
autoencoder.fit(seq_encoded, seq_encoded, epochs=100)




Epoch 1/100
1/1 [==============================] - 1s 1s/step - loss: 3.0437
Epoch 2/100
1/1 [==============================] - 0s 17ms/step - loss: 3.0363
Epoch 3/100
1/1 [==============================] - 0s 15ms/step - loss: 3.0290
Epoch 4/100
1/1 [==============================] - 0s 13ms/step - loss: 3.0216
Epoch 5/100
1/1 [==============================] - 0s 12ms/step - loss: 3.0143
Epoch 6/100
1/1 [==============================] - 0s 11ms/step - loss: 3.0070
Epoch 7/100
1/1 [==============================] - 0s 11ms/step - loss: 2.9997
Epoch 8/100
1/1 [==============================] - 0s 11ms/step - loss: 2.9924
Epoch 9/100
1/1 [==============================] - 0s 11ms/step - loss: 2.9852
Epoch 10/100
1/1 [==============================] - 0s 12ms/step - loss: 2.9779
Epoch 11/100
1/1 [==============================] - 0s 13ms/step - loss: 2.9707
Epoch 12/100
1/1 [==============================] - 0s 12ms/step - loss: 2.9635
Epoch 13/100
1/1 [==============================] -

In [ ]:
# Use the autoencoder to encode and decode the sequence
seq_decoded = autoencoder.predict(seq_encoded)

1/1 [==============================] - 0s 301ms/step


In [ ]:
# Compute reconstruction error metrics
cross_entropy = -np.mean(np.sum(seq_encoded * np.log(seq_decoded), axis=-1))
same_aa_accuracy = np.mean(np.argmax(seq_encoded, axis=-1) == np.argmax(seq_decoded, axis=-1))
most_common_aa_accuracy = np.mean(np.argmax(seq_encoded.sum(axis=0), axis=-1) == np.argmax(seq_decoded.sum(axis=0), axis=-1))

print("Cross-Entropy:", cross_entropy)
print("Accuracy (Same aa):", same_aa_accuracy)
print("Accuracy (Mode aa):", most_common_aa_accuracy)


Cross-Entropy: 2.2128596658537374
Accuracy (Same aa): 0.8224852071005917
Accuracy (Mode aa): 0.8224852071005917


In [ ]:
# Decode and print the original and reconstructed sequences
print("Original sequence:")
print(decode_sequence(seq_encoded[0]))
print("Reconstructed sequence:")
print(decode_sequence(seq_decoded[0]))


Original sequence:
----------------------TLNEAKQQGLVGETFSGYLAVV--DIQAQALVIKINQAREKKYAEVATSNNISTEQVAKLAGEKLVNRAEPGEYVQG-NGQWLKK---------MSSLILSGCV-RLEVATPEKPININMNVKIEHEIHVKIDKQIEEMLKSNTGLF
Reconstructed sequence:
----------------------VLNEAKQQGLVGEVGIGGLAVV--EIQAQALVIKINQAEEKKGAEVAVINNIIVEQVAKLAGEKLVNEAEIGEGVQG-NGQVLKK---------MIILILIG-V-ELEVAVIEKIININMNVKIEKEIKVKIEKQIEEMLKINVGLG


WE HAVE DONE WITH THE AMION ACIDS SEQUNCES AS = 'ACDEFGHIKLMNPQRSTVWY-'

In [96]:
# now we need to do encoding and decoing for the missing amion acids and we need to train the data 

Now i am taking the amni sequences as 'S, A, G, N, G, R, Y, E, I, G, A,N'

In [98]:
#  Encoder 

# Define the amino acid alphabet
amino_acids = 'ACDEFGHIKLMNPQRSTVWY-'

def one_hot_encoding(seq):
    # Create a dictionary to map each amino acid to its index in the alphabet
    aa_to_index = {aa: i for i, aa in enumerate(amino_acids)}
    # Initialize the one-hot encoded array
    one_hot = np.zeros((len(seq), len(amino_acids)))
    # Set the appropriate elements to 1
    for i, aa in enumerate(seq):
        if aa in aa_to_index:
            one_hot[i, aa_to_index[aa]] = 1
    return one_hot

# Define the size of the latent space
latent_dim = 32

# Define the architecture of the autoencoder
input_seq = Input(shape=(None, len(amino_acids)))
encoded = Dense(latent_dim, activation='relu')(input_seq)
decoded = Dense(len(amino_acids), activation='softmax')(encoded)
autoencoder = Model(input_seq, decoded)

# Compile the autoencoder model
autoencoder.compile(optimizer='adam', loss='categorical_crossentropy')

# Encode the sequence using one-hot encoding
seq_encoded = one_hot_encoding(seq).reshape(1, -1, len(amino_acids))

# Train the autoencoder on the encoded sequence
autoencoder.fit(seq_encoded, seq_encoded, epochs=100)


Epoch 1/100
1/1 [==============================] - 1s 691ms/step - loss: 2.9850
Epoch 2/100
1/1 [==============================] - 0s 22ms/step - loss: 2.9780
Epoch 3/100
1/1 [==============================] - 0s 14ms/step - loss: 2.9710
Epoch 4/100
1/1 [==============================] - 0s 26ms/step - loss: 2.9640
Epoch 5/100
1/1 [==============================] - 0s 16ms/step - loss: 2.9570
Epoch 6/100
1/1 [==============================] - 0s 15ms/step - loss: 2.9500
Epoch 7/100
1/1 [==============================] - 0s 14ms/step - loss: 2.9429
Epoch 8/100
1/1 [==============================] - 0s 11ms/step - loss: 2.9359
Epoch 9/100
1/1 [==============================] - 0s 14ms/step - loss: 2.9289
Epoch 10/100
1/1 [==============================] - 0s 14ms/step - loss: 2.9218
Epoch 11/100
1/1 [==============================] - 0s 14ms/step - loss: 2.9148
Epoch 12/100
1/1 [==============================] - 0s 14ms/step - loss: 2.9077
Epoch 13/100
1/1 [==============================

In [99]:
# Use the autoencoder to encode and decode the sequence
seq_decoded = autoencoder.predict(seq_encoded)

1/1 [==============================] - 0s 111ms/step


In [121]:
# Compute reconstruction error metrics
cross_entropy = -np.mean(np.sum(seq_encoded * np.log(seq_decoded), axis=-1))
same_aa_accuracy = np.mean(np.argmax(seq_encoded, axis=-1) == np.argmax(seq_decoded, axis=-1))
most_common_aa_accuracy = np.mean(np.argmax(seq_encoded.sum(axis=0), axis=-1) == np.argmax(seq_decoded.sum(axis=0), axis=-1))

In [122]:
print("Cross-entropy:", cross_entropy)
print("Same amino acid accuracy:", same_aa_accuracy)
print("Most common amino acid accuracy:", most_common_aa_accuracy)

Cross-entropy: 2.2881636252770057
Same amino acid accuracy: 0.863905325443787
Most common amino acid accuracy: 0.863905325443787


In [123]:
# Decode and print the original and reconstructed sequences
print("Original sequence:")
print(decode_sequence(seq_encoded[0]))
print("Reconstructed sequence:")
print(decode_sequence(seq_decoded[0]))


Original sequence:
MMKILWGLTLS--LLTSSVWALTLDEARTQGRVGETLNGYLVALKNDAETQKLVLDINRARRASYQQLADSNHLPVDEVAKMAGQKLVERARPGEYVQGINGKWLRK-MKMIIVMLSVFFMVVSCTPRIEVAAPEQPITINMNVKIEHEIHIKVDKDVEELLKSRSDLF
Reconstructed sequence:
MMKILWGLTLD--LLTDDVWALTLDEARTQGRVGETLKGLLVALKKDAETQKLVLDIKRARRADLQQLADDKHLPVDEVAKMAGQKLVERARPGELVQGIKGKWLRK-MKMIIVMLDVGGMVVDVTPRIEVAAPEQPITIKMKVKIEHEIHIKVDKDVEELLKDRDDLG


In [102]:
# Decoding with the missing amino acids 

from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model
import numpy as np

def one_hot_encoding(seq):
    # Define the amino acid alphabet
    amino_acids = 'ACDEFGHIKLMNPQRSTVWY-'
    # Create a dictionary to map each amino acid to its index in the alphabet
    aa_to_index = {aa: i for i, aa in enumerate(amino_acids)}
    # Initialize the one-hot encoded array
    one_hot = np.zeros((len(seq), len(amino_acids)))
    # Set the appropriate elements to 1
    for i, aa in enumerate(seq):
        if aa in aa_to_index:
            one_hot[i, aa_to_index[aa]] = 1
    return one_hot

def decode_sequence(one_hot_seq):
    # Define the amino acid alphabet
    amino_acids = 'ACDEFGHIKLMNPQRSTVWY-'
    # Convert the one-hot encoded sequence back into an amino acid sequence
    return ''.join([amino_acids[i] for i in np.argmax(one_hot_seq, axis=-1)])

# Define the size of the latent space
latent_dim = 32

# Define the autoencoder architecture
input_seq = Input(shape=(None, len(amino_acids)))
encoded = Dense(latent_dim, activation='relu')(input_seq)
decoded = Dense(len(amino_acids), activation='softmax')(encoded)
autoencoder = Model(input_seq, decoded)

# Compile the autoencoder model
autoencoder.compile(optimizer='adam', loss='categorical_crossentropy')


# Encode the sequence using one-hot encoding
seq_encoded = one_hot_encoding(seq).reshape(1, -1, len(amino_acids))

# Train the autoencoder on the encoded sequence
autoencoder.fit(seq_encoded, seq_encoded, epochs=100)




Epoch 1/100
1/1 [==============================] - 1s 736ms/step - loss: 3.0488
Epoch 2/100
1/1 [==============================] - 0s 13ms/step - loss: 3.0425
Epoch 3/100
1/1 [==============================] - 0s 14ms/step - loss: 3.0361
Epoch 4/100
1/1 [==============================] - 0s 16ms/step - loss: 3.0298
Epoch 5/100
1/1 [==============================] - 0s 12ms/step - loss: 3.0234
Epoch 6/100
1/1 [==============================] - 0s 13ms/step - loss: 3.0171
Epoch 7/100
1/1 [==============================] - 0s 13ms/step - loss: 3.0108
Epoch 8/100
1/1 [==============================] - 0s 12ms/step - loss: 3.0044
Epoch 9/100
1/1 [==============================] - 0s 19ms/step - loss: 2.9981
Epoch 10/100
1/1 [==============================] - 0s 15ms/step - loss: 2.9917
Epoch 11/100
1/1 [==============================] - 0s 12ms/step - loss: 2.9853
Epoch 12/100
1/1 [==============================] - 0s 18ms/step - loss: 2.9789
Epoch 13/100
1/1 [==============================

In [118]:
# Use the autoencoder to encode and decode the sequence
seq_decoded = autoencoder.predict(seq_encoded)

1/1 [==============================] - 0s 32ms/step


In [120]:
print("Cross-entropy:", cross_entropy)
print("Same amino acid accuracy:", same_aa_accuracy)
print("Most common amino acid accuracy:", most_common_aa_accuracy)

Cross-entropy: 2.2881636252770057
Same amino acid accuracy: 0.863905325443787
Most common amino acid accuracy: 0.863905325443787


In [117]:
# Decode and print the original and reconstructed sequences
print("Original sequence:")
print(decode_sequence(seq_encoded[0]))
print("Reconstructed sequence:")
print(decode_sequence(seq_decoded[0]))


Original sequence:
MMKILWGLTLS--LLTSSVWALTLDEARTQGRVGETLNGYLVALKNDAETQKLVLDINRARRASYQQLADSNHLPVDEVAKMAGQKLVERARPGEYVQGINGKWLRK-MKMIIVMLSVFFMVVSCTPRIEVAAPEQPITINMNVKIEHEIHIKVDKDVEELLKSRSDLF
Reconstructed sequence:
MMKILWGLTLD--LLTDDVWALTLDEARTQGRVGETLKGLLVALKKDAETQKLVLDIKRARRADLQQLADDKHLPVDEVAKMAGQKLVERARPGELVQGIKGKWLRK-MKMIIVMLDVGGMVVDVTPRIEVAAPEQPITIKMKVKIEHEIHIKVDKDVEELLKDRDDLG
